name: Build DatBot
on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

#    - name: What is the OS
#      run: echo ${{ runner.os }}
#
    - name: Set up Linux
      if: runner.os == 'Linux'
      run: sudo apt install libboost-program-options-dev libyaml-cpp-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Release
