name: Build DatBot
on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Windows
      if: runner.os == 'Windows'
      run: vcpkg install rxcpp rxcpp:x64-windows yaml-cpp yaml-cpp:x64-windows

    - name: Set up Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install libboost-program-options-dev
        sudo vcpkg install rxcpp yaml-cpp

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake ../DatBot -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . -v --config Release
