name: Build DatBot
on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Windows
      if: runner.os == 'Windows'
      run: | 
        vcpkg install rxcpp rxcpp:x64-windows yaml-cpp yaml-cpp:x64-windows
        echo '::set-env name=CMAKE_FLAGS::"-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"'

    - name: Set up Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install libboost-dev libboost-program-options-dev
        sudo vcpkg install rxcpp yaml-cpp
        echo ::set-env name=CMAKE_FLAGS::-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Set up macOS
      if: runner.os == 'macOS'
      run: |
        brew install boost yaml-cpp
        git clone --depth=1 "https://github.com/ReactiveX/RxCpp.git"
        cmake -E make_directory RxCppBuild
        cd RxCppBuild
        cmake ../RxCpp
        sudo make install

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake --trace ../DatBot -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . -v --config Release
