name: Build DatBot
on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        cxx: [g++, clang++]

    steps:
    - uses: actions/checkout@v2

    - name: Where is vcpkg?
      if: runner.os != 'Windows'
      run: which vcpkg

    - name: What are the variables?
      run: set

    - name: Set up Windows
      if: runner.is == 'Windows'
	  run: vcpkg install boost boost-program-options rxcpp yaml-cpp

    - name: Set up Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install libboost-program-options-dev libyaml-cpp-dev
        sudo vcpkg install rxcpp

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=${{matrix.cxx}}

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Release
